### ISSUE TITLE
TypeError: 'HTTPError' object is not subscriptable

### ISSUE THREAD

**Issue by danieljimeneznz** [university-of-auckland/conflex#7]
https://github.com/university-of-auckland/conflex/blob/a7036babf66012e256b5e4d9c09fcf0bf9a10492/confluence/api.py#L259-L262

Causing the following issues below:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/capsule-wiki/__main__.py", line 258, in <module>
    run(config, False, config_modified)
  File "/opt/capsule-wiki/__main__.py", line 189, in run
    space_id = ConfluenceAPI.get_homepage_id_of_space(space)
  File "/opt/capsule-wiki/confluence/api.py", line 261, in get_homepage_id_of_space
    (space, int(response['_expandable']['homepage'].replace('/rest/api/content/', ''))))
TypeError: 'HTTPError' object is not subscriptable
```

**Comment by danieljimeneznz** [comment]
Issue happens if the user is not able to make a request to get the space, i.e. the space does not exist or the user has insufficient permissions to access the space. Spaces should be handled separately (either in a separate thread or if an error occurs, the application should move on).

**Comment by danieljimeneznz** [comment]
Hotfix fixes issue.
